name: brassicate

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - click
  - cookiecutter
  - coverage
  - doc8
  - flake8
  - pip
  - pylint
  - pytest
  - pytest-runner
  - pyyaml
  - rope
  - sphinx
  - tox
  - twine
  - watchdog
  - wheel

  # Pip packages
  - pip:
    - bump2version
